export const FETCH_TODOS_REQUEST = 'FETCH_DATA_REQUEST'
export const FETCH_TODOS_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_TODOS_FAILURE = 'FETCH_DATA_FAILURE'

export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST'
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE'
